//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bazy
{
    using System;
    using System.Collections.Generic;
    
    public partial class companies
    {
        public companies()
        {
            this.freights = new HashSet<freights>();
            this.freights1 = new HashSet<freights>();
        }
    
        public int Id { get; set; }
        public int CityId { get; set; }
        public int CompanyId { get; set; }
        public string Address { get; set; }
        public string Comment { get; set; }
    
        public virtual cities_list cities_list { get; set; }
        public virtual ICollection<freights> freights { get; set; }
        public virtual ICollection<freights> freights1 { get; set; }
        public virtual companyNameList company_name_list { get; set; }
    }
}
