//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bazy
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyNameList
    {
        public companyNameList()
        {
            this.companies = new HashSet<companies>();
        }
    
        public int Id { get; set; }
        public string Company { get; set; }
    
        public virtual ICollection<companies> companies { get; set; }
    }
}
