//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bazy
{
    using System;
    using System.Collections.Generic;
    
    public partial class drivers
    {
        public drivers()
        {
            this.shipping = new HashSet<shipping>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Wage { get; set; }
        public string ADR_License { get; set; }
        public string Employed { get; set; }
        public string Busy { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<shipping> shipping { get; set; }
    }
}
