//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bazy
{
    using System;
    using System.Collections.Generic;
    
    public partial class freights
    {
        public freights()
        {
            this.shipping = new HashSet<shipping>();
        }
    
        public int Id { get; set; }
        public int CargoId { get; set; }
        public int From { get; set; }
        public int To { get; set; }
        public System.DateTime ScheduledArrive { get; set; }
        public byte Amount { get; set; }
        public int Weight { get; set; }
        public string Comment { get; set; }
    
        public virtual cargo cargo { get; set; }
        public virtual companies companies { get; set; }
        public virtual companies companies1 { get; set; }
        public virtual ICollection<shipping> shipping { get; set; }
    }
}
