//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bazy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projektEntities : DbContext
    {
        public projektEntities()
            : base("name=projektEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cargo> cargo { get; set; }
        public DbSet<cars> cars { get; set; }
        public DbSet<cities_list> cities_list { get; set; }
        public DbSet<companies> companies { get; set; }
        public DbSet<companyNameList> company_name_list { get; set; }
        public DbSet<drivers> drivers { get; set; }
        public DbSet<freights> freights { get; set; }
        public DbSet<shipping> shipping { get; set; }
    }
}
