//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bazy
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipping
    {
        public int Id { get; set; }
        public int DriverId { get; set; }
        public int CarId { get; set; }
        public int FreightId { get; set; }
        public System.DateTime DepartTime { get; set; }
        public Nullable<System.DateTime> ArriveTime { get; set; }
        public string Delivered { get; set; }
        public string Comment { get; set; }
    
        public virtual cars cars { get; set; }
        public virtual drivers drivers { get; set; }
        public virtual freights freights { get; set; }
    }
}
